//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer CB0UBO
// {
//
//   float4 CB0_m0;                     // Offset:    0 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// S0                                sampler      NA          NA             s0      1 
// T0                                texture  float4          2d             t0      1 
// U0                                    UAV  float4          2d             u0      1 
// U1                                    UAV    uint         buf             u1      1 
// U2                                    UAV  float4          2d             u2      1 
// U3                                    UAV  float4          2d             u3      1 
// U4                                    UAV  float4          2d             u4      1 
// U5                                    UAV  float4          2d             u5      1 
// U6                                    UAV  float4          2d             u6      1 
// U7                                    UAV  float4          2d             u7      1 
// CB0UBO                            cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[1], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_uav_typed_texture2d (float,float,float,float) u0
dcl_uav_typed_buffer (uint,uint,uint,uint) u1
dcl_uav_typed_texture2d (float,float,float,float) u2
dcl_uav_typed_texture2d (float,float,float,float) u3
dcl_uav_typed_texture2d (float,float,float,float) u4
dcl_uav_typed_texture2d (float,float,float,float) u5
dcl_uav_typed_texture2d (float,float,float,float) u6
dcl_uav_typed_texture2d (float,float,float,float) u7
dcl_input vThreadIDInGroupFlattened
dcl_input vThreadGroupID.xy
dcl_temps 9
dcl_indexableTemp x0[16], 4
dcl_tgsm_structured g0, 4, 256
dcl_tgsm_structured g1, 4, 1
dcl_thread_group 256, 1, 1
ushr r0.xyz, vThreadIDInGroupFlattened.xxxx, l(3, 2, 7, 0)
and r0.xy, r0.yxyy, l(6, 4, 0, 0)
ubfe r1.xyz, l(3, 1, 2, 0), l(3, 6, 1, 0), vThreadIDInGroupFlattened.xxxx
bfi r0.w, l(1), l(0), vThreadIDInGroupFlattened.x, r0.x
imad r0.w, r1.y, l(8), r0.w
iadd r0.y, r0.y, r1.z
imad r0.y, r0.z, l(8), r0.y
ishl r1.w, r0.x, l(1)
bfi r2.x, l(1), l(1), vThreadIDInGroupFlattened.x, l(0)
iadd r2.y, r1.w, r2.x
imad r3.y, r1.y, l(16), r2.y
ishl r2.yz, r1.xxzx, l(0, 1, 1, 0)
bfi r2.z, l(3), l(0), r2.z, r2.y
imad r3.z, r0.z, l(16), r2.z
utof r2.zw, cb0[0].zzzw
imad r4.xy, vThreadGroupID.xyxx, l(64, 64, 0, 0), r3.yzyy
iadd r4.xy, r4.xyxx, l(1, 1, 0, 0)
utof r4.xy, r4.xyxx
div r4.yz, r4.xxyx, r2.zzwz
gather4_indexable(texture2d)(float,float,float,float) r5.xyzw, r4.yzyy, t0.xyzw, s0.x
max r5.xy, r5.zxzz, r5.wyww
max r5.x, r5.y, r5.x
mov x0[0].x, r5.x
imad r6.y, vThreadGroupID.x, l(32), r0.w
imad r6.z, vThreadGroupID.y, l(32), r0.y
store_uav_typed u0.xyzw, r6.yzzz, r5.xxxx
iadd r5.xy, r3.yzyy, l(32, 32, 0, 0)
iadd r5.zw, r0.wwwy, l(0, 0, 16, 16)
imad r5.xy, vThreadGroupID.xyxx, l(64, 64, 0, 0), r5.xyxx
or r5.xy, r5.xyxx, l(33, 33, 0, 0)
utof r5.xy, r5.xyxx
div r4.xw, r5.xxxy, r2.zzzw
gather4_indexable(texture2d)(float,float,float,float) r7.xyzw, r4.xzxx, t0.xyzw, s0.x
max r2.zw, r7.zzzx, r7.wwwy
max r2.z, r2.w, r2.z
mov x0[4].x, r2.z
imad r6.x, vThreadGroupID.x, l(32), r5.z
store_uav_typed u0.xyzw, r6.xzzz, r2.zzzz
gather4_indexable(texture2d)(float,float,float,float) r7.xyzw, r4.ywyy, t0.xyzw, s0.x
max r2.zw, r7.zzzx, r7.wwwy
max r2.z, r2.w, r2.z
mov x0[8].x, r2.z
imad r6.w, vThreadGroupID.y, l(32), r5.w
store_uav_typed u0.xyzw, r6.ywww, r2.zzzz
gather4_indexable(texture2d)(float,float,float,float) r4.xyzw, r4.xwxx, t0.xyzw, s0.x
max r2.zw, r4.zzzx, r4.wwwy
max r2.z, r2.w, r2.z
mov x0[12].x, r2.z
store_uav_typed u0.xyzw, r6.xwww, r2.zzzz
ult r4.xyz, l(1, 2, 6, 0), cb0[0].xxxx
if_nz r4.x
  ishl r5.xyzw, r1.xzzw, l(2, 2, 3, 6)
  bfi r2.z, l(4), l(0), r5.y, r5.x
  imad r2.z, r0.z, l(32), r2.z
  ult r2.w, vThreadIDInGroupFlattened.x, l(64)
  ishl r4.x, r2.y, l(2)
  bfi r4.x, l(5), l(0), r5.z, r4.x
  imad r4.x, r0.z, l(64), r4.x
  ishl r5.xy, vThreadGroupID.xyxx, l(4, 4, 0, 0)
  ishl r4.w, r0.x, l(6)
  bfi r4.w, l(1), l(6), vThreadIDInGroupFlattened.x, r4.w
  imad r4.w, r1.y, l(512), r4.w
  iadd r5.z, r2.z, r4.w
  ushr r5.z, r5.z, l(2)
  imad r5.w, r2.x, l(64), r5.w
  imad r5.w, r1.y, l(1024), r5.w
  iadd r6.x, r4.x, r5.w
  iadd r5.w, r5.w, l(64)
  iadd r4.x, r4.x, r5.w
  ushr r4.x, r4.x, l(2)
  iadd r5.w, r4.x, l(1)
  ushr r6.x, r6.x, l(2)
  iadd r6.y, r6.x, l(1)
  mov r6.z, l(0)
  loop 
    uge r6.w, r6.z, l(4)
    breakc_nz r6.w
    ishl r6.w, r6.z, l(2)
    mov r7.x, x0[r6.w + 0].x
    store_structured g0.x, r5.z, l(0), r7.x
    sync_g_t
    if_nz r2.w
      ld_structured r7.x, r5.w, l(0), g0.xxxx
      ld_structured r7.y, r6.y, l(0), g0.xxxx
      max r7.x, r7.y, r7.x
      ld_structured r7.y, r4.x, l(0), g0.xxxx
      ld_structured r7.z, r6.x, l(0), g0.xxxx
      max r7.y, r7.z, r7.y
      max r7.x, r7.y, r7.x
      mov x0[r6.w + 0].x, r7.x
      bfi r6.w, l(1), l(3), r6.z, l(0)
      iadd r6.w, r0.w, r6.w
      iadd r8.x, r5.x, r6.w
      ushr r6.w, r6.z, l(1)
      ishl r6.w, r6.w, l(3)
      iadd r6.w, r0.y, r6.w
      iadd r8.yzw, r5.yyyy, r6.wwww
      store_uav_typed u2.xyzw, r8.xyzw, r7.xxxx
    endif 
    sync_g_t
    iadd r6.z, r6.z, l(1)
  endloop 
  if_nz r2.w
    mov r2.w, x0[0].x
    store_structured g0.x, r5.z, l(0), r2.w
    iadd r2.w, r4.w, l(512)
    iadd r4.x, r2.w, r2.z
    ushr r4.x, r4.x, l(2)
    mov r5.x, x0[4].x
    store_structured g0.x, r4.x, l(0), r5.x
    iadd r2.z, r2.z, l(32)
    iadd r4.x, r2.z, r4.w
    ushr r4.x, r4.x, l(2)
    mov r4.w, x0[8].x
    store_structured g0.x, r4.x, l(0), r4.w
    iadd r2.z, r2.z, r2.w
    ushr r2.z, r2.z, l(2)
    mov r2.w, x0[12].x
    store_structured g0.x, r2.z, l(0), r2.w
  endif 
endif 
if_nz r4.y
  sync_g_t
  ult r2.z, vThreadIDInGroupFlattened.x, l(64)
  if_nz r2.z
    ishl r2.y, r2.y, l(2)
    ishl r2.z, r1.z, l(3)
    bfi r2.y, l(5), l(0), r2.z, r2.y
    imad r2.y, r0.z, l(64), r2.y
    iadd r2.z, r2.y, l(4)
    ishl r1.w, r1.w, l(6)
    imad r1.w, r2.x, l(64), r1.w
    imad r1.w, r1.y, l(1024), r1.w
    imad r2.x, l(1), l(64), r1.w
    iadd r2.w, r2.z, r2.x
    ushr r2.w, r2.w, l(2)
    ld_structured r2.w, r2.w, l(0), g0.xxxx
    iadd r2.z, r2.z, r1.w
    ushr r2.z, r2.z, l(2)
    ld_structured r2.z, r2.z, l(0), g0.xxxx
    max r2.z, r2.z, r2.w
    iadd r2.w, r1.w, r2.y
    ushr r2.w, r2.w, l(2)
    ld_structured r2.w, r2.w, l(0), g0.xxxx
    iadd r2.x, r2.y, r2.x
    ushr r2.x, r2.x, l(2)
    ld_structured r2.x, r2.x, l(0), g0.xxxx
    max r2.x, r2.x, r2.w
    max r2.x, r2.x, r2.z
    ishl r2.zw, vThreadGroupID.xxxy, l(0, 0, 3, 3)
    iadd r5.xyzw, r0.wyyy, r2.zwww
    store_uav_typed u3.xyzw, r5.xyzw, r2.xxxx
    bfi r1.w, l(1), l(6), r0.y, r1.w
    iadd r1.w, r2.y, r1.w
    ushr r1.w, r1.w, l(2)
    store_structured g0.x, r1.w, l(0), r2.x
  endif 
  ult r1.w, l(3), cb0[0].x
  if_nz r1.w
    sync_g_t
    ult r1.w, vThreadIDInGroupFlattened.x, l(16)
    if_nz r1.w
      ishl r2.xy, r0.xxxx, l(2, 8, 0, 0)
      bfi r1.w, l(1), l(2), vThreadIDInGroupFlattened.x, l(0)
      iadd r2.z, r2.x, r1.w
      imad r2.z, r1.y, l(32), r2.z
      ishl r4.xy, r1.xzxx, l(4, 4, 0, 0)
      bfi r2.w, l(6), l(0), r4.y, r4.x
      bfi r2.w, l(7), l(0), r2.w, vThreadIDInGroupFlattened.x
      iadd r4.x, r2.w, l(8)
      bfi r2.y, l(1), l(8), vThreadIDInGroupFlattened.x, r2.y
      imad r2.y, r1.y, l(2048), r2.y
      iadd r2.y, r2.y, l(128)
      iadd r2.y, r2.w, r2.y
      ushr r2.y, r2.y, l(2)
      ld_structured r2.y, r2.y, l(0), g0.xxxx
      ishl r2.x, r2.x, l(6)
      imad r1.w, r1.w, l(64), r2.x
      imad r1.w, r1.y, l(2048), r1.w
      iadd r2.x, r1.w, r2.w
      ushr r2.x, r2.x, l(2)
      ld_structured r2.x, r2.x, l(0), g0.xxxx
      max r2.x, r2.x, r2.y
      iadd r4.yw, r1.wwww, l(0, 192, 0, 64)
      iadd r4.xy, r4.xxxx, r4.ywyy
      ushr r4.xy, r4.xyxx, l(2, 2, 0, 0)
      ld_structured r1.w, r4.x, l(0), g0.xxxx
      ld_structured r2.y, r4.y, l(0), g0.xxxx
      max r1.w, r1.w, r2.y
      max r1.w, r1.w, r2.x
      ishl r2.xy, vThreadGroupID.xyxx, l(2, 2, 0, 0)
      iadd r5.xyzw, r0.wyyy, r2.xyyy
      store_uav_typed u4.xyzw, r5.xyzw, r1.wwww
      iadd r2.x, r0.y, r2.z
      ishl r2.x, r2.x, l(6)
      iadd r2.x, r2.w, r2.x
      ushr r2.x, r2.x, l(2)
      store_structured g0.x, r2.x, l(0), r1.w
    endif 
    ult r1.w, l(4), cb0[0].x
    if_nz r1.w
      sync_g_t
      ult r1.w, vThreadIDInGroupFlattened.x, l(4)
      if_nz r1.w
        ishl r0.x, r0.x, l(3)
        bfi r1.w, l(1), l(3), vThreadIDInGroupFlattened.x, l(0)
        iadd r0.x, r0.x, r1.w
        imad r0.x, r1.y, l(64), r0.x
        ishl r1.xy, r1.xzxx, l(5, 5, 0, 0)
        bfi r1.x, l(7), l(0), r1.y, r1.x
        imad r0.z, r0.z, l(256), r1.x
        iadd r1.x, r0.z, l(16)
        imad r1.yz, r0.wwww, l(0, 8, 8, 0), l(0, 5, 4, 0)
        iadd r1.yz, r1.yyzy, r3.zzzz
        ishl r1.yz, r1.yyzy, l(0, 6, 6, 0)
        iadd r1.y, r1.x, r1.y
        ushr r1.y, r1.y, l(2)
        ld_structured r1.y, r1.y, l(0), g0.xxxx
        iadd r1.w, r0.x, l(1)
        iadd r1.w, r1.w, r3.z
        ishl r1.w, r1.w, l(6)
        iadd r1.x, r1.x, r1.w
        ushr r1.x, r1.x, l(2)
        ld_structured r1.x, r1.x, l(0), g0.xxxx
        max r1.x, r1.x, r1.y
        iadd r1.y, r0.z, r1.z
        ushr r1.y, r1.y, l(2)
        ld_structured r1.y, r1.y, l(0), g0.xxxx
        iadd r0.x, r0.x, r3.z
        ishl r0.x, r0.x, l(6)
        iadd r0.x, r0.z, r0.x
        ushr r0.x, r0.x, l(2)
        ld_structured r0.x, r0.x, l(0), g0.xxxx
        max r0.x, r0.x, r1.y
        max r0.x, r0.x, r1.x
        ishl r1.xy, vThreadGroupID.xyxx, l(1, 1, 0, 0)
        iadd r2.xyzw, r0.wyyy, r1.xyyy
        store_uav_typed u5.xyzw, r2.xyzw, r0.xxxx
        iadd r0.y, r0.w, r3.z
        ishl r0.y, r0.y, l(4)
        store_structured g0.x, r0.y, l(0), r0.x
      endif 
      ult r0.x, l(5), cb0[0].x
      if_nz r0.x
        sync_g_t
        ult r0.x, vThreadIDInGroupFlattened.x, l(1)
        if_nz r0.x
          ld_structured r0.x, l(48), l(0), g0.xxxx
          ld_structured r0.y, l(32), l(0), g0.xxxx
          max r0.x, r0.y, r0.x
          ld_structured r0.y, l(16), l(0), g0.xxxx
          ld_structured r0.z, l(0), l(0), g0.xxxx
          max r0.y, r0.z, r0.y
          max r0.x, r0.y, r0.x
          store_uav_typed u6.xyzw, vThreadGroupID.xyyy, r0.xxxx
        endif 
      endif 
    endif 
  endif 
endif 
if_nz r4.z
  if_z vThreadIDInGroupFlattened.x
    imm_atomic_iadd r0.x, u1, l(0), l(1)
    store_structured g1.x, l(0), l(0), r0.x
  endif 
  sync_g_t
  iadd r0.x, l(-1), cb0[0].y
  ld_structured r0.y, l(0), l(0), g1.xxxx
  ieq r0.x, r0.y, r0.x
  if_nz r0.x
    store_uav_typed u7.xyzw, r3.yzzz, l(0,0,0,0)
    iadd r3.xw, r3.yyyz, l(1, 0, 0, 1)
    store_uav_typed u7.xyzw, r3.xzzz, l(0,0,0,0)
    store_uav_typed u7.xyzw, r3.ywww, l(0,0,0,0)
    store_uav_typed u7.xyzw, r3.xwww, l(0,0,0,0)
  endif 
endif 
ret 
// Approximately 278 instruction slots used
