//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[1], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_uav_typed_texture2d (float,float,float,float) u0
dcl_uav_structured u1, 4
dcl_uav_typed_texture2d (float,float,float,float) u2
dcl_uav_typed_texture2d (float,float,float,float) u3
dcl_uav_typed_texture2d (float,float,float,float) u4
dcl_uav_typed_texture2d (float,float,float,float) u5
dcl_uav_typed_texture2d (float,float,float,float) u6
dcl_uav_typed_texture2d (float,float,float,float) u7
dcl_input vThreadIDInGroupFlattened
dcl_input vThreadGroupID.xy
dcl_temps 8
dcl_indexableTemp x0[4], 4
dcl_tgsm_structured g0, 64, 16
dcl_tgsm_raw g1, 4
dcl_thread_group 256, 1, 1
and r0.x, vThreadIDInGroupFlattened.x, l(63)
ubfe r0.yzw, l(0, 4, 3, 1), l(0, 2, 3, 6), vThreadIDInGroupFlattened.xxxx
and r0.y, r0.y, l(6)
bfi r1.x, l(1), l(0), vThreadIDInGroupFlattened.x, r0.y
ubfe r0.x, l(2), l(1), r0.x
bfi r1.y, l(2), l(0), r0.x, r0.z
imad r2.y, r0.w, l(8), r1.x
ushr r1.x, vThreadIDInGroupFlattened.x, l(7)
imad r2.z, r1.x, l(8), r1.y
ishl r1.y, r0.y, l(1)
bfi r1.y, l(1), l(1), vThreadIDInGroupFlattened.x, r1.y
imad r3.w, r0.w, l(16), r1.y
ishl r1.y, r0.z, l(1)
bfi r1.z, l(2), l(1), r0.x, r1.y
imad r3.y, r1.x, l(16), r1.z
imad r1.zw, vThreadGroupID.xxxy, l(0, 0, 64, 64), r3.wwwy
imad r4.xyzw, vThreadGroupID.xyyy, l(32, 32, 32, 32), r2.yzzz
iadd r1.zw, r1.zzzw, l(0, 0, 1, 1)
utof r1.zw, r1.zzzw
utof r5.xy, cb0[0].zwzz
div r1.zw, r1.zzzw, r5.xxxy
gather4_indexable(texture2d)(float,float,float,float) r6.xyzw, r1.zwzz, t0.xyzw, s0.x
max r1.zw, r6.yyyw, r6.xxxz
max r1.z, r1.w, r1.z
mov x0[0].x, r1.z
store_uav_typed u0.xyzw, r4.xyzw, r1.zzzz
iadd r3.xz, r3.wwyw, l(32, 0, 32, 0)
imad r4.xyzw, vThreadGroupID.xyxy, l(64, 64, 64, 64), r3.xywz
iadd r2.xw, r2.yyyz, l(16, 0, 0, 16)
imad r6.xyzw, vThreadGroupID.xyyy, l(32, 32, 32, 32), r2.xzzz
iadd r4.xyzw, r4.xyzw, l(1, 1, 1, 1)
utof r4.xyzw, r4.xyzw
div r4.xyzw, r4.xyzw, r5.xyxy
gather4_indexable(texture2d)(float,float,float,float) r7.xyzw, r4.xyxx, t0.xyzw, s0.x
max r1.zw, r7.yyyw, r7.xxxz
max r1.z, r1.w, r1.z
mov x0[1].x, r1.z
store_uav_typed u0.xyzw, r6.xyzw, r1.zzzz
imad r6.xyzw, vThreadGroupID.xyyy, l(32, 32, 32, 32), r2.ywww
gather4_indexable(texture2d)(float,float,float,float) r4.xyzw, r4.zwzz, t0.xyzw, s0.x
max r1.zw, r4.yyyw, r4.xxxz
max r1.z, r1.w, r1.z
mov x0[2].x, r1.z
store_uav_typed u0.xyzw, r6.xyzw, r1.zzzz
imad r1.zw, vThreadGroupID.xxxy, l(0, 0, 64, 64), r3.xxxz
imad r4.xyzw, vThreadGroupID.xyyy, l(32, 32, 32, 32), r2.xwww
or r1.zw, r1.zzzw, l(0, 0, 33, 33)
utof r1.zw, r1.zzzw
div r1.zw, r1.zzzw, r5.xxxy
gather4_indexable(texture2d)(float,float,float,float) r5.xyzw, r1.zwzz, t0.xyzw, s0.x
max r1.zw, r5.yyyw, r5.xxxz
max r1.z, r1.w, r1.z
mov x0[3].x, r1.z
store_uav_typed u0.xyzw, r4.xyzw, r1.zzzz
ult r4.xyz, l(1, 2, 6, 0), cb0[0].xxxx
if_nz r4.x
  ishl r1.z, r0.z, l(2)
  bfi r1.z, l(2), l(2), r0.x, r1.z
  imad r1.z, r1.x, l(32), r1.z
  ult r1.w, vThreadIDInGroupFlattened.x, l(64)
  iadd r2.x, r3.w, l(1)
  ishl r2.w, r1.y, l(2)
  bfi r2.w, l(2), l(3), r0.x, r2.w
  imad r2.w, r1.x, l(64), r2.w
  ishl r5.xyzw, vThreadGroupID.xyyy, l(4, 4, 4, 4)
  mov r4.x, l(0)
  loop 
    uge r4.w, r4.x, l(4)
    breakc_nz r4.w
    mov r4.w, x0[r4.x + 0].x
    store_structured g0.x, r2.y, r1.z, r4.w
    sync_g_t
    if_nz r1.w
      ld_structured r6.xy, r3.w, r2.w, g0.xyxx
      ld_structured r6.zw, r2.x, r2.w, g0.xxxy
      max r6.xy, r6.zwzz, r6.xyxx
      max r4.w, r6.y, r6.x
      mov x0[r4.x + 0].x, r4.w
      bfi r6.x, l(1), l(3), r4.x, l(0)
      iadd r6.x, r2.y, r6.x
      ushr r7.x, r4.x, l(1)
      ishl r7.x, r7.x, l(3)
      iadd r6.yzw, r2.zzzz, r7.xxxx
      iadd r6.xyzw, r5.xyzw, r6.xyzw
      store_uav_typed u2.xyzw, r6.xyzw, r4.wwww
    endif 
    sync_g_t
    iadd r4.x, r4.x, l(1)
  endloop 
  if_nz r1.w
    mov r1.w, x0[0].x
    store_structured g0.x, r2.y, r1.z, r1.w
    iadd r1.w, r2.y, l(8)
    mov r2.x, x0[1].x
    store_structured g0.x, r1.w, r1.z, r2.x
    mov r2.x, x0[2].x
    iadd r1.z, r1.z, l(32)
    store_structured g0.x, r2.y, r1.z, r2.x
    mov r2.x, x0[3].x
    store_structured g0.x, r1.w, r1.z, r2.x
  endif 
endif 
if_nz r4.y
  sync_g_t
  ult r1.z, vThreadIDInGroupFlattened.x, l(64)
  if_nz r1.z
    iadd r1.z, r3.w, l(1)
    ishl r1.y, r1.y, l(2)
    bfi r1.y, l(2), l(3), r0.x, r1.y
    imad r1.y, r1.x, l(64), r1.y
    ld_structured r1.w, r3.w, r1.y, g0.xxxx
    ld_structured r2.x, r1.z, r1.y, g0.xxxx
    iadd r2.w, r1.y, l(4)
    ld_structured r4.x, r3.w, r2.w, g0.xxxx
    ld_structured r1.z, r1.z, r2.w, g0.xxxx
    max r1.w, r1.w, r2.x
    max r1.z, r1.z, r4.x
    max r1.z, r1.z, r1.w
    ishl r5.xyzw, vThreadGroupID.xyyy, l(3, 3, 3, 3)
    iadd r5.xyzw, r2.yzzz, r5.xyzw
    store_uav_typed u3.xyzw, r5.xyzw, r1.zzzz
    bfi r1.w, l(1), l(0), r2.z, r3.w
    store_structured g0.x, r1.w, r1.y, r1.z
  endif 
  ult r1.y, l(3), cb0[0].x
  if_nz r1.y
    sync_g_t
    ult r1.y, vThreadIDInGroupFlattened.x, l(16)
    if_nz r1.y
      ishl r1.yw, r0.yyyz, l(0, 2, 0, 4)
      bfi r1.y, l(1), l(2), vThreadIDInGroupFlattened.x, r1.y
      imad r1.y, r0.w, l(32), r1.y
      imad r1.z, r2.y, l(4), l(2)
      iadd r2.xw, r1.yyyy, l(1, 0, 0, 3)
      bfi r1.w, l(2), l(4), r0.x, r1.w
      imad r1.w, r1.x, l(128), r1.w
      ld_structured r4.x, r1.y, r1.w, g0.xxxx
      ld_structured r1.z, r1.z, r1.w, g0.xxxx
      iadd r4.y, r1.w, l(8)
      ld_structured r2.x, r2.x, r4.y, g0.xxxx
      ld_structured r2.w, r2.w, r4.y, g0.xxxx
      max r1.z, r1.z, r4.x
      max r2.x, r2.w, r2.x
      max r1.z, r1.z, r2.x
      ishl r5.xyzw, vThreadGroupID.xyyy, l(2, 2, 2, 2)
      iadd r5.xyzw, r2.yzzz, r5.xyzw
      store_uav_typed u4.xyzw, r5.xyzw, r1.zzzz
      iadd r1.y, r2.z, r1.y
      store_structured g0.x, r1.y, r1.w, r1.z
    endif 
    ult r1.y, l(4), cb0[0].x
    if_nz r1.y
      sync_g_t
      ult r1.y, vThreadIDInGroupFlattened.x, l(4)
      if_nz r1.y
        ishl r0.yz, r0.yyzy, l(0, 3, 5, 0)
        bfi r0.y, l(1), l(3), vThreadIDInGroupFlattened.x, r0.y
        imad r0.y, r0.w, l(64), r0.y
        iadd r0.w, r3.y, r0.y
        imad r1.yz, r2.yyyy, l(0, 8, 8, 0), l(0, 4, 5, 0)
        iadd r0.y, r0.y, l(1)
        iadd r0.y, r3.y, r0.y
        iadd r1.yz, r3.yyyy, r1.yyzy
        bfi r0.x, l(2), l(5), r0.x, r0.z
        imad r0.x, r1.x, l(256), r0.x
        ld_structured r0.z, r0.w, r0.x, g0.xxxx
        ld_structured r0.w, r1.y, r0.x, g0.xxxx
        iadd r0.x, r0.x, l(16)
        ld_structured r0.y, r0.y, r0.x, g0.xxxx
        ld_structured r0.x, r1.z, r0.x, g0.xxxx
        max r0.xz, r0.xxwx, r0.yyzy
        max r0.x, r0.x, r0.z
        ishl r1.xyzw, vThreadGroupID.xyyy, l(1, 1, 1, 1)
        iadd r1.xyzw, r2.yzzz, r1.xyzw
        store_uav_typed u5.xyzw, r1.xyzw, r0.xxxx
        iadd r0.y, r2.y, r3.y
        store_structured g0.x, r0.y, l(0), r0.x
      endif 
      ult r0.x, l(5), cb0[0].x
      if_nz r0.x
        sync_g_t
        ult r0.x, vThreadIDInGroupFlattened.x, l(1)
        if_nz r0.x
          ld_structured r0.x, l(0), l(0), g0.xxxx
          ld_structured r0.y, l(1), l(0), g0.xxxx
          ld_structured r0.z, l(2), l(0), g0.xxxx
          ld_structured r0.w, l(3), l(0), g0.xxxx
          max r0.x, r0.y, r0.x
          max r0.y, r0.w, r0.z
          max r0.x, r0.y, r0.x
          store_uav_typed u6.xyzw, vThreadGroupID.xyyy, r0.xxxx
        endif 
      endif 
    endif 
  endif 
endif 
if_nz r4.z
  if_z vThreadIDInGroupFlattened.x
    imm_atomic_iadd r0.x, u1, l(0, 0, 0, 0), l(1)
    store_raw g1.x, l(0), r0.x
  endif 
  sync_g_t
  ld_raw r0.x, l(0), g1.xxxx
  iadd r0.y, cb0[0].y, l(-1)
  ieq r0.x, r0.y, r0.x
  if_nz r0.x
    store_uav_typed u7.xyzw, r3.wyyy, l(0,0,0,0)
    iadd r3.xz, r3.wwyw, l(1, 0, 1, 0)
    store_uav_typed u7.xyzw, r3.xyyy, l(0,0,0,0)
    store_uav_typed u7.xyzw, r3.wzzz, l(0,0,0,0)
    store_uav_typed u7.xyzw, r3.xzzz, l(0,0,0,0)
  endif 
endif 
ret 
// Approximately 0 instruction slots used
